### ISSUE TITLE
The regex in Spirit

### ISSUE THREAD

**Issue by X-zhihao** [ilwoof/LogGD#1]
I see you used Drain to parse logs. So i want to know the details in Spirit.log.
For example ,i used 
 'HDFS': {
        'log_file': 'HDFS/HDFS_2k.log',
        'log_format': '<Date> <Time> <Pid> <Level> <Component>: <Content>',
        'regex': [r'blk_-?\d+', r'(\d+\.){3}\d+(:\d+)?'],
        'st': 0.5,
        'depth': 4
       }, in HDFS.log. 

Thanks!

**Comment by ilwoof** [comment]
The following is the regex configuration I used for Spirit. But there are still some noises. So, you can further improve the configuration by yourself.

    'Spirit': {
        'log_file': 'spirit/Spirit1G.log',
        'log_format': '<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Content>',
        'regex': [r'(\d+\.){3}\d+', r'(\/.*?\.[\S:]+)', r'(/[a-zA-Z0-9_-]+)+',
                  r'((?<=[^A-Za-z0-9])|^)([\-\+]?\d+)((?=[^A-Za-z0-9])|$)',
                  r'((?<=[^A-Za-z0-9])|^)(0x[a-f0-9A-F]+)((?=[^A-Za-z0-9])|$)'],
        'st': 0.5,
        'depth': 4
    },
